### ISSUE TITLE
ESP32 version 2.0.5

### ISSUE THREAD

**Issue by Erik84750** [josef2600/Brownout-detection-problem-in-Arduino-and-ESP32-C3#1]
Thanks a lot for that update Josef2600.
Yet the modifications you propose already are present in the 4 involved files for version 2.0.5.

I don't know if this is coincidence but bronw-out detection level 7 already is default configured.

**Comment by josef2600** [comment]
edit 1:
it appears I made few confusions! First, ESP32 and ESP32C3 are way different from each other. C3 has a very very high voltage trigger. E.g., Esp32 lowest trigger level is around 2.44 volt, but C3 is over 3 volts. So that is why C3 has a big problem.
Second:
CONFIG_ESP32C3_BROWNOUT_DET_LVL 7 is the highest level, meaning, the highest voltage needed. I think it is 3.2-volt trigger. It is a very happy trigger chip! And CONFIG_ESP32C3_BROWNOUT_DET_LVL 1 is around 3 (a bit more than 3) volt. If you use usb or 5 volts for input and give it to a low drop regulator, it is high possibility to reset the chip. If you want to be sure, do this:
Enable debug level info. Then try to connect to it via WIFI or do something that causes reset. Then when it resets, it prints in serial port, what caused the reset. If it is brownout reset, it prints it.

**Comment by josef2600** [comment]
and farther more:
https://github.com/josef2600/Brownout-detection-problem-in-Arduino-and-ESP32-C3/blob/main/disable%20BROWN_OUT%20%20detector

**Comment by Marcel-G** [comment]
I cannot confirm if this data is correct but it's at least how espressif presents the settings in their configuration UI:

For `esp32` the lowest brownout level (level 0) is also the lowest voltage option:

https://github.com/espressif/esp-idf/blob/a5b261f699808efdacd287adbded5b718dffd14e/components/esp_system/port/soc/esp32/Kconfig.system#L12-L38

For `esp32c3` it appears that it's the opposite case. The lowest brownout level (level 2) is the **highest** voltage option

https://github.com/espressif/esp-idf/blob/a5b261f699808efdacd287adbded5b718dffd14e/components/esp_system/port/soc/esp32c3/Kconfig.system#L11-L33

In both cases espressif/esp-idf already sets the default to the lowest voltage option. It sounds like Arduino SDK uses the same defaults
